sudo: false
dist: trusty

language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.2

cache:
  apt: true
  directories:
    - $HOME/.stack/
    - .stack-work/

before_install: mkdir -p $HOME/.local/bin
install:
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true

before_script: rm -rf .build
script: ./Shakefile.hs build-error

env:
  global:
    - PATH=$HOME/.local/bin:/opt/ghc/8.2.2/bin:$PATH
